name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Reinhart-py
          outputs: |
            dist/snake-light.svg?color_snake=#475569&color_dots=#F1F5F9,#CBD5E1,#94A3B8,#475569,#0F172A
            dist/snake-dark.svg?palette=github-dark&color_snake=#94A3B8&color_dots=#0F172A,#1E293B,#475569,#94A3B8,#F8FAFC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update contribution snake [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
