name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Reinhart-py
          outputs: |
            dist/snake-light.svg?color_snake=#475569&color_dots=#F1F5F9,#CBD5E1,#94A3B8,#475569,#0F172A
            dist/snake-dark.svg?palette=github-dark&color_snake=#94A3B8&color_dots=#0F172A,#1E293B,#475569,#94A3B8,#F8FAFC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Snake SVGs
        run: |
          git config --local user.email "reinhart96x@gmail.com"
          git config --local user.name "Reinhart-py"
          git add dist/snake-dark.svg dist/snake-light.svg
          git diff-index --quiet HEAD || git commit -m "chore: update contribution snake SVGs [skip ci]"
          git push origin main
